### ISSUE TITLE
Add conditional rendering to Login and Register components on front page

### ISSUE THREAD

**Issue by tachorzy** [tachorzy/COSC4353-Project-Group39#38]
- If a user is logged in the Login and Register components shouldn't appear on the front page.
- Instead display some user information (not sensitive stuff of course) to fill up the space with something relevant.
- When designing I'll try to make the theme consistent with the other components and make some subtle changes across the website.

If you want to help with this part let me know, otherwise I'll just take it on in my own time, sometime before the due date, since this is pretty low priority.

**Comment by Tinachinehkesh** [comment]
ok
